/*
* The data that we want to map
handle: Twitter Handle
lat :
lng :
urlProfile : Profile Tw
text: tuit
icon: normal or heavy
*/
var tuit = [
	{'handle': twHandle1,
	'lat': lat1,
	'lng': lng1,
  'text': text1,
  'url': urlProfile1,
	'badge':heavyBadge,
  'icon': ich1},
	{'handle': 'tHandle2',
	'lat': lat1,
	'lng': lng2,
  'text': text2,
  'url': urlProfile2,
	'badge':heavyBadge,
  'icon': ich2},
	{'handle': 'tHandle3',
	'lat': lat3,
	'lng': lng3,
  'url': urlProfile3,
  'text':text3,
	'badge':heavyBadge,
  'icon': ich3},
	{'handle': 'tHandle4',
	'lat': lat4,
	'lng': lng4,
  'text': text4,
  'url':urlProfile4,
	'badge':heavyBadge,
  'icon': ich4},
	{'handle': 'tHandle5',
	'lat': lat5,
	'lng': lng5,
  'url': urlProfile5,
  'text': text5,
	'badge':heavyBadge,
  'icon': ich5},
	{'handle': 'tHandle6',
	'lat': lat6,
	'lng': lng6,
  'text': text6,
  'url': urlProfile6,
	'badge':heavyBadge,
  'icon': ich6},
	{'handle': 'tHandle7',
	'lat': lat7,
	'lng': lng7,
  'text':text7,
  'url':urlProfile7,
	'badge':heavyBadge,
  'icon': ich7},
	{'handle': 'tHandle8',
	'lat': lat8,
	'lng': lng8,
  'text': text8,
  'url': urlProfile8,
	'badge':heavyBadge,
  'icon': ich8},
	{'handle': 'tHandle9',
	'lat': lat9,
	'lng': lng9,
  'text': text9,
  'url': urlProfile9,
	'badge':heavyBadge,
  'icon': ich9}
];

var normal = [
	{'handle': 'tHandle10',
	'lat': lat10,
	'lng': lng10,
  'text': text10,
  'url': urlProfile10,
  'icon': icn1},
	{'handle': 'tHandle11',
	'lat': lat11,
	'lng': lng11,
	'text': text11,
  'url': urlProfile11,
  'icon': icn2},
	{'handle': 'tHandle12',
	'lat': lat12,
	'lng': lng12,
  'text':text12,
  'url':urlProfile12,
  'icon': icn3},
	{'handle': 'tHandle13',
	'lat': lat13,
	'lng': lng13,
  'text': text13,
	'url': urlProfile13,
  'icon': icn4},
	{'handle': 'tHandle14',
	'lat': lat14,
	'lng': lng14,
  'text': text14,
  'url':urlProfile14,
  'icon': icn5}
];
